"""Generate resilience test files from observed failures.

Mirrors the Lark sponsor challenge example («coding agent setup that
listens for failing tests and creates PRs to fix them»). For each
failing test reported by Lark, the generator picks the relevant chaos
scenario(s) and emits a runnable pytest file that reproduces the
failure under controlled conditions.

The mapping is deterministic and rule-based on the failure string.
That keeps generation auditable: the engineer can read the rule that
matched and tweak it. A future iteration can swap in an LLM-based
classifier behind the same Generator interface.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

# Order matters: first match wins.
_RULES: list[tuple[re.Pattern[str], list[str]]] = [
    (re.compile(r"\b429\b|too many requests", re.I), ["rate_limit"]),
    (re.compile(r"\b502\b|bad gateway", re.I), ["llm_5xx"]),
    (re.compile(r"\b503\b|service unavailable", re.I), ["partial_outage"]),
    (re.compile(r"\b504\b|timeout", re.I), ["llm_timeout"]),
    (re.compile(r"\b402\b|quota|cost", re.I), ["cost_exceeded"]),
    (re.compile(r"connect.*(error|refused|reset)", re.I), ["network_blip"]),
    (re.compile(r"empty|truncated|stream.*drop", re.I), ["stream_stall"]),
    (re.compile(r"mcp|tool.*error|jsonrpc", re.I), ["mcp_error"]),
    (re.compile(r"wrong.*model|model.*mismatch", re.I), ["wrong_model_returned"]),
]


@dataclass
class GeneratedTest:
    """Result of generating one test file from a Lark failure."""

    test_name: str
    scenarios: list[str]
    file_path: Path
    source: str


def pick_scenarios(failure_text: str) -> list[str]:
    """Return the scenario names that best match a free-text failure.

    Falls back to ``llm_5xx`` if nothing matches; that is the most generic
    transient-failure scenario and a sane default.
    """
    matched: list[str] = []
    for pattern, scenarios in _RULES:
        if pattern.search(failure_text):
            matched.extend(scenarios)
    return matched or ["llm_5xx"]


_TEMPLATE = '''"""Auto-generated resilience test for {test_name!r}.

Generated by pytest-resilience-agent from a Lark-reported failure.

Original failure text:
    {failure_text}

Chosen scenarios: {scenarios}
"""

from __future__ import annotations

import httpx
import pytest


@pytest.mark.resilience(scenarios={scenarios!r})
def {function_name}(chaos):
    """Reproduce the original failure under controlled chaos.

    The chaos fixture installs the named scenarios at the HTTP layer.
    Replace the body below with the call from your real agent code; the
    boilerplate POST below just exercises the gateway to prove the
    scenarios are active.
    """
    with httpx.Client() as client:
        response = client.post(chaos.target_gateway_url, json={{"q": 1}})
        # When the scenarios are correct, the response status / shape
        # mirrors the original failure. Add an assertion on the contract
        # your real agent should hold:
        # assert agent.handle_response(response).fallback_used
        assert response is not None
'''


def generate_test(
    test_name: str,
    failure_text: str,
    out_dir: Path,
) -> GeneratedTest:
    """Write a resilience test file for one failure. Return the artefact."""
    scenarios = pick_scenarios(failure_text)
    safe_name = re.sub(r"[^a-zA-Z0-9_]+", "_", test_name).strip("_") or "auto_test"
    if not safe_name.startswith("test_"):
        safe_name = f"test_{safe_name}"
    file_path = out_dir / f"{safe_name}_resilience.py"
    function_name = safe_name + "_resilience"
    source = _TEMPLATE.format(
        test_name=test_name,
        failure_text=failure_text,
        scenarios=scenarios,
        function_name=function_name,
    )
    out_dir.mkdir(parents=True, exist_ok=True)
    file_path.write_text(source, encoding="utf-8")
    return GeneratedTest(
        test_name=test_name,
        scenarios=scenarios,
        file_path=file_path,
        source=source,
    )
