"""Capture the rich demo output as a PNG for README embedding.

We capture the full-loop demo stdout into a Rich-recorded SVG and then
re-render through cairosvg or fall back to a plain PNG generated by
Pillow drawing the captured ANSI-stripped lines on a dark background.

Run::

    python docs/screenshot/render_demo_screenshot.py

Output: docs/screenshot/demo_full_loop.png
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

OUT_PATH = Path(__file__).parent / "demo_full_loop.png"

ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")


def capture_demo_output() -> str:
    """Run the full-loop demo and return the captured stdout text."""
    result = subprocess.run(
        [sys.executable, "-X", "utf8", "-m", "demo.run_full_loop"],
        capture_output=True,
        text=True,
        cwd=Path(__file__).resolve().parents[2],
    )
    return result.stdout


def strip_ansi(text: str) -> str:
    """Remove ANSI escape sequences from captured output."""
    return ANSI_RE.sub("", text)


def render_to_png(text: str, out_path: Path) -> None:
    """Render the cleaned text to a PNG on a dark background."""
    lines = text.splitlines() or [""]
    font_size = 18
    line_height = font_size + 6
    margin = 28
    fonts = [
        r"C:\Windows\Fonts\consola.ttf",
        r"C:\Windows\Fonts\cour.ttf",
        "/System/Library/Fonts/Menlo.ttc",
        "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
    ]
    font = None
    for path in fonts:
        try:
            font = ImageFont.truetype(path, font_size)
            break
        except OSError:
            continue
    if font is None:
        font = ImageFont.load_default()

    max_width = 0
    for line in lines:
        bbox = font.getbbox(line)
        max_width = max(max_width, bbox[2] - bbox[0])

    width = max_width + 2 * margin
    height = line_height * len(lines) + 2 * margin
    image = Image.new("RGB", (width, height), (12, 14, 22))
    draw = ImageDraw.Draw(image)

    fg_default = (220, 220, 230)
    accent = (250, 155, 80)
    indigo = (140, 170, 255)
    green = (140, 220, 150)

    for idx, line in enumerate(lines):
        y = margin + idx * line_height
        if "PASS" in line:
            colour = green
        elif "FAIL" in line:
            colour = (240, 130, 130)
        elif line.strip().startswith("Mock Lark") or "demo" in line.lower():
            colour = indigo
        elif "Lark reports" in line or "generated" in line or "Running" in line:
            colour = accent
        else:
            colour = fg_default
        draw.text((margin, y), line, fill=colour, font=font)

    image.save(out_path, "PNG")
    print(f"wrote {out_path}")


def main() -> int:
    out_path = OUT_PATH
    out_path.parent.mkdir(parents=True, exist_ok=True)
    raw = capture_demo_output()
    cleaned = strip_ansi(raw)
    render_to_png(cleaned, out_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
